### ISSUE TITLE
Error importing module l1tf

### ISSUE THREAD

**Issue by Mark531** [elsonidoq/py-l1tf#2]
Hello,

I downloaded the repo and installed it via "pip install .". It worked fine. But when I call "import l1tf", I get this error:

> ModuleNotFoundError: No module named 'pandas_wrapper'

It seems it is necessary and is missing from the install.

Regards,
Mark

**Comment by elsonidoq** [comment]
I did some small fixes, it should work now

Thanks!

**Comment by Mark531** [comment]
It's working now, thanks!
